### ISSUE TITLE
Crash on boot if large log file is present in src/main/resources

### ISSUE THREAD

**Issue by nromito** [spacer59/cribl-log-collection#2]
```
java.lang.ClassCastException: class java.lang.OutOfMemoryError cannot be cast to class xsbti.FullReload (java.lang.OutOfMemoryError is in module java.base of loader 'bootstrap'; xsbti.FullReload is in unnamed module of loader 'app')
	at sbt.internal.XMainConfiguration.run(XMainConfiguration.java:59)
	at sbt.xMain.run(Main.scala:46)
	at xsbt.boot.Launch$.$anonfun$run$1(Launch.scala:149)
	at xsbt.boot.Launch$.withContextLoader(Launch.scala:176)
	at xsbt.boot.Launch$.run(Launch.scala:149)
	at xsbt.boot.Launch$.$anonfun$apply$1(Launch.scala:44)
	at xsbt.boot.Launch$.launch(Launch.scala:159)
	at xsbt.boot.Launch$.apply(Launch.scala:44)
	at xsbt.boot.Launch$.apply(Launch.scala:21)
	at xsbt.boot.Boot$.runImpl(Boot.scala:78)
	at xsbt.boot.Boot$.run(Boot.scala:73)
	at xsbt.boot.Boot$.main(Boot.scala:21)
	at xsbt.boot.Boot.main(Boot.scala)
[error] [launcher] error during sbt launcher: java.lang.ClassCastException: class java.lang.OutOfMemoryError cannot be cast to class xsbti.FullReload (java.lang.OutOfMemoryError is in module java.base of loader 'bootstrap'; xsbti.FullReload is in unnamed module of loader 'app')
```

I added a 5GB log file to the resource dir and the app crashed on boot

**Comment by spacer59** [comment]
I tried this and it failed as well. The exception was different for some reason but the cause seems to be the same - large file in resources directory. sbt includes resources in the class path and it seems to be not happy with the  file size.

```
java.lang.RuntimeException: Could not copy '/Users/kdeshpande/work/cribl-log-collection/src/main/resources/machine-1/large-file.log' to '/Users/kdeshpande/work/cribl-log-collection/target/scala-2.13/classes/machine-1/large-file.log' (21211480/21212280 bytes copied)
```

I moved the files outside of resources to the project root and the application seems to boot fine now regardless of file size. Please let me know if this alternative approach works for you.

PR: https://github.com/spacer59/cribl-log-collection

**Comment by spacer59** [comment]
Note I was unable to commit a large file since github imposes a limit but I used one locally for testing.

**Comment by spacer59** [comment]
Resolved after https://github.com/spacer59/cribl-log-collection/pull/5
